Baias/urls.py
from django.urls import path

from . import views

app_name = "baias"

urlpatterns = [
    path('listar/', views.listar_baias, name='listar'),
    path('adicionar/', views.adicionar_baia, name='adicionar'),
    path('deletar/<int:pk>/', views.deletar_baia, name="deletar"),
    path('editar/<int:pk>', views.editar_baia, name="editar"),
    path('listar_lv/', views.listar_baias_lv.as_view(), name='listar_lv'),
    path('adicionar_cv/', views.adicionar_baias_cv.as_view(), name='adicionar_cv'),
    path('deletar_dv/<int:pk>/', views.deletar_baia_dv.as_view(), name='deletar_dv'),
    path('editar_uv/<int:pk>', views.editar_baia_uv.as_view(), name="editar_uv"),
]

Funcionario/urls.py
from django.urls import path

from . import views

app_name = "funcionario"

urlpatterns = [
    path('listar/', views.listar_funcionarios, name='listar'),
    path('adicionar/', views.adicionar_funcionarios, name='adicionar'),
    path('deletar/<int:pk>/', views.deletar_funcionario, name="deletar"),
    path('editar/<int:pk>', views.editar_funcionario, name="editar"),
    path('listar_lv/', views.listar_funcionarios_lv.as_view(), name='listar_lv'),
    path('adicionar_cv/', views.adicionar_funcionarios_cv.as_view(), name='adicionar_cv'),
    path('deletar_dv/<int:pk>/', views.deletar_funcionario_dv.as_view(), name='deletar_dv'),
    path('editar_uv/<int:pk>', views.editar_funcionario_uv.as_view(), name="editar_uv"),
]

ranchcontrol_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('funcionario/', include('Funcionario.urls')),
    path('baias/', include('Baias.urls')),
    path('animal/', include('Animal.urls')),
    path('admin/', admin.site.urls),
]

Funcionario/models.py
from django.db import models
# Create your models here.
class Funcionario(models.Model):
  nome = models.CharField(max_length=300, null=False)
  funcao = models.CharField(max_length=300, null=False)
  def __str__(self):
    return self.nome + " - " + self.funcao;

Funcionario/forms.py
from django import forms
from django.db import connection

from django.contrib import messages

from django.core.exceptions import ValidationError

from .models import Funcionario

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = ['nome', 'funcao']

    def clean(self):
        cleaned_data = super().clean()
        nome = cleaned_data.get("nome")

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Funcionario_funcionario WHERE nome=%s", [nome])
            resultado_funcionario = cursor.fetchall()

        if (len(resultado_funcionario) != 0):
            raise ValidationError("Já foi criado um funcionario com este nome. Escolha outro nome.")

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = ['nome', 'funcao']

    def clean(self):
        cleaned_data = super().clean()
        nome = cleaned_data.get("nome")

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Funcionario_funcionario WHERE nome=%s", [nome])
            resultado_funcionario = cursor.fetchall()

Funcionario/views.py
from django.http import HttpResponse

from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from django.db import connection
from collections import namedtuple

from django.contrib import messages

from .models import Funcionario

from .forms import FuncionarioForm
from .forms import UpdateForm


def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def listar_funcionarios(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM Funcionario_funcionario ORDER BY id", [])
        #resultado = cursor.fetchall()

        resultado = namedtuplefetchall(cursor)
    return render(request, 'Funcionario/listar.html',
            {'funcionarios': resultado}
            )
class listar_funcionarios_lv(ListView):
    model = Funcionario
    template_name = "Funcionario/listar_lv.html"

def adicionar_funcionarios(request):
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            funcao = form.cleaned_data['funcao']
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO Funcionario_funcionario (nome, funcao) "
                                "VALUES (%s, %s)",
                                [nome, funcao])
                resultado = cursor.fetchall()
            return redirect('funcionario:listar')
    else:
        form = FuncionarioForm()
    return render(request, 'Funcionario/adicionar.html',
                {'form': form}
                )
class adicionar_funcionarios_cv(CreateView):
    model = Funcionario
    template_name = "Funcionario/adicionar_cv.html"
    fields = ['nome', 'funcao']
    success_url = reverse_lazy('funcionario:listar_lv')

    def form_valid(self, form):
        if Funcionario.objects.filter(nome = form.cleaned_data['nome']):
            messages.add_message(self.request, messages.WARNING,
                                 "Já existe um funcionario com esse nome.")
            return self.render_to_response(self.get_context_data(form=form))
        else:
            return super(adicionar_funcionarios_cv, self).form_valid(form)                

def deletar_funcionario(request, pk):
    if request.method == 'POST':

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Funcionario_funcionario WHERE id=%s", [pk])
            nome_funcionario = cursor.fetchall()[0][1]

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias_Funcionarios WHERE funcionario_id=%s", [pk])
            resultado = cursor.fetchall()

        if len(resultado) == 0:
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM Baias_baias_Funcionarios WHERE funcionario_id=%s", [pk])
                cursor.execute("DELETE FROM Funcionario_funcionario WHERE id=%s", [pk])
            messages.add_message(request, messages.ERROR, 'Funcionario ' + nome_funcionario + ' deletado com sucesso.')
            return redirect('funcionario:listar')

        else:
            messages.add_message(request, messages.ERROR, 'Não é possível deletar o funcionario ' + nome_funcionario + '. Há baias associados a este produto.')
            return redirect('funcionario:listar')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Funcionario_funcionario WHERE id=%s", [pk])
            resultado = namedtuplefetchall(cursor)
        return render(request, "Funcionario/confirmar_deletar.html", {'funcionario': resultado[0]})

class deletar_funcionario_dv(DeleteView):
    model = Funcionario
    template_name = "Funcionario/confirmar_deletar_dv.html"
    success_url = reverse_lazy('funcionario:listar')


def editar_funcionario(request, pk):
    if request.method == 'POST':
        form = UpdateForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            funcao = form.cleaned_data['funcao']

            with connection.cursor() as cursor:
                cursor.execute("UPDATE Funcionario_funcionario SET nome=%s, funcao=%s WHERE id=%s",
                                [nome, funcao, pk])
                resultado = cursor.fetchall()
            return redirect('funcionario:listar')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Funcionario_funcionario WHERE id=%s", [pk])
            resultado_funcionario = namedtuplefetchall(cursor)
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias_Funcionarios WHERE id=%s", [resultado_funcionario[0].id])
            resultado_baias = namedtuplefetchall(cursor)
        form = UpdateForm(initial={'nome': resultado_funcionario[0].nome,
                                    'funcao': resultado_funcionario[0].funcao,
                                    })
    return render(request, 'Funcionario/editar.html',
                {'form': form}
                )

class editar_funcionario_uv(UpdateView):
    model = Funcionario
    fields = ['nome', 'funcao']
    template_name = "Funcionario/editar_uv.html"
    success_url = reverse_lazy('funcionario:listar')

templates/Funcionario/adicionar.html
{% extends "base.html" %}

{% block titulo %}
Adicionar Funcionarios
{% endblock %}

{% block titulo_pagina %}
Cadastrar
{% endblock %}

{% block conteudo %}
    <div class="w-50 formulario">
      <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" class="btn btn-primary" value="Cadastrar">
      </form>
    </div>
{% endblock %}

templates/Funcionario/adicionar_cv.html
{% extends "base.html" %}

{% block titulo %}
Adicionar Funcionarios
{% endblock %}

{% block titulo_pagina %}
Cadastrar
{% endblock %}

{% block conteudo %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    
    <div class="w-50 formulario">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
{% endblock %}

templates/Funcionario/confirmar_deletar.html
{% extends "base.html" %}

{% block titulo %}
Confirmação remoção
{% endblock %}

{% block titulo_pagina %}
Você tem certeza que deseja remover este funcionario?
{% endblock %}

{% block conteudo %}
  <div class="w-25 mt-4">
    <form method="post">
      {% csrf_token %}
      <p><strong>Nome: </strong> {{funcionario.nome}} </p>
      <p><strong>Descrição: </strong> {{funcionario.funcao}} </p>
      <input type="submit" class="btn btn-primary" value="Confirmar">
    </form>
  </div>

{% endblock %}

templates/Funcionario/confirmar_deletar_dv.html
{% extends "base.html" %}

{% block titulo %}
Confirmação remoção
{% endblock %}

{% block titulo_pagina %}
Você tem certeza que deseja remover este funcionario?
{% endblock %}

{% block conteudo %}
  <div class="w-25 mt-4">
    <form method="post">
      {% csrf_token %}
      <p><strong>Nome: </strong> {{object.nome}} </p>
      <p><strong>Descrição: </strong> {{object.funcao}} </p>
      <input type="submit" class="btn btn-primary" value="Confirmar">
    </form>
  </div>

{% endblock %}

templates/Funcionario/editar.html
{% extends "base.html" %}

{% block titulo %}
Editar Funcionários
{% endblock %}

{% block titulo_pagina %}
Editar
{% endblock %}

{% block conteudo %}
  <div class="w-50 formulario">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Atualizar">
    </form>
  </div>

{% endblock %}

templates/Funcionario/listar.html
{% extends "base.html" %}

{% block titulo %}
Listar Funcionarios
{% endblock %}

{% block titulo_pagina %}
Funcionarios
{% endblock %}

{% block conteudo %}
  {% if messages %}
      <ul>
          {% for message in messages %}
              <li class="alert alert-warning">{{ message }}</li>
          {% endfor %}
      </ul>
  {% endif %}

  {% if funcionarios %}
    <ul class="list-group div35">
      {% for funcionario in funcionarios %}
      <li class="list-group-item">
        <strong>{{funcionario.id}}: {{ funcionario.nome }} - {{ funcionario.funcao }}</strong>
        <span class="span">
          <a href="{% url 'funcionario:editar' pk=funcionario.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-pencil" style="color:#F2BE24"></i>
          </a>
          <a href="{% url 'funcionario:deletar' pk=funcionario.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-trash" style="color: var(--main-red)"></i>
          </a>
        </span>
      </li>
      {% endfor %}
    </ul>
  {% else %}
  <p>Não há funcionários cadastrados.</p>
  {% endif %}
{% endblock %}

templates/Funcionario/listar_lv.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{% static 'ranchcontrol/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'ranchcontrol/styles.css' %}">

  <title>Ranch Control - web</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-dark navbar-expand-md" style="background-color: var(--main-light-green);">
      <div class="container-fluid">
        <a class="navbar-brand ms-5" href="http://localhost:8000/">
          <img src="{% static 'ranchcontrol/vaqueiro.svg' %}" alt="" width="30" height="24"
            class="d-inline-block align-text-top">
          Ranch Control
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Funcionarios
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/funcionario/adicionar">Adicionar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/funcionario/listar">Listar</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Animal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/animal/adicionar">Adicionar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/animal/listar">Listar</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Baias
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/baias/adicionar">Adicionar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/baias/listar">Listar</a></li>
              </ul>
            </li>
          </ul>
      </div>
    </nav>
  </header>

  <main class="container mt-5">
    <h3>
      Listar Funcionários LV
    </h3>
    
    {% if object_list  %}
    <ul class="list-group div35">
      {% for funcionario in object_list  %}
      <li class="list-group-item">
        <strong>{{funcionario.id}}: {{ funcionario.nome }} - {{ funcionario.funcao }}</strong>
        <span class="span">
          <a href="{% url 'funcionario:editar' pk=funcionario.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-pencil" style="color:#F2BE24"></i>
          </a>
          <a href="{% url 'funcionario:deletar' pk=funcionario.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-trash" style="color: var(--main-red)"></i>
          </a>
        </span>
      </li>
      {% endfor %}
    </ul>
  {% else %}
  <p>Não há produtos cadastrados.</p>
  {% endif %}
   
  </main>

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{% static 'ranchcontrol/script.js' %}"></script>
</body>

</html>