Baias/urls.py
from django.urls import path

from . import views

app_name = "baias"

urlpatterns = [
    path('listar/', views.listar_baias, name='listar'),
    path('adicionar/', views.adicionar_baia, name='adicionar'),
    path('deletar/<int:pk>/', views.deletar_baia, name="deletar"),
    path('editar/<int:pk>', views.editar_baia, name="editar"),
    path('listar_lv/', views.listar_baias_lv.as_view(), name='listar_lv'),
    path('adicionar_cv/', views.adicionar_baias_cv.as_view(), name='adicionar_cv'),
    path('deletar_dv/<int:pk>/', views.deletar_baia_dv.as_view(), name='deletar_dv'),
    path('editar_uv/<int:pk>', views.editar_baia_uv.as_view(), name="editar_uv"),
]

ranchcontrol_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('funcionario/', include('Funcionario.urls')),
    path('baias/', include('Baias.urls')),
    path('animal/', include('Animal.urls')),
    path('admin/', admin.site.urls),
]

Baias/models.py
from django.db import models
from Funcionario.models import Funcionario
from Animal.models import Animal

# Create your models here.


class Baias(models.Model):
    nome_baia = models.CharField(max_length=300, null=False)
    capacidade = models.PositiveIntegerField(null=False)
    definicao = models.TextField()
    Funcionarios = models.ManyToManyField(Funcionario)


    def __str__(self):
        return self.nome_baia

Baias/forms.py
from django import forms
from django.db import connection

from django.contrib import messages

from django.core.exceptions import ValidationError

from .models import Baias

class BaiasForm(forms.ModelForm):
    class Meta:
        model = Baias
        fields = ['nome_baia', 'capacidade', 'definicao', 'Funcionarios' ]

    def clean(self):
        cleaned_data = super().clean()
        nome_baia = cleaned_data.get("nome_baia")

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias WHERE nome_baia=%s", [nome_baia])
            resultado_baia = cursor.fetchall()

        if (len(resultado_baia) != 0):
            raise ValidationError("Já foi criado uma baia com este nome. Escolha outro nome.")

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Baias
        fields = ['nome_baia', 'capacidade', 'definicao', 'Funcionarios']

    def clean(self):
        cleaned_data = super().clean()
        nome_baia = cleaned_data.get("nome_baia")

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias WHERE nome_baia=%s", [nome_baia])
            resultado_baia = cursor.fetchall()

Baias/views.py
from django.http import HttpResponse

from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from django.db import connection
from collections import namedtuple

from django.contrib import messages

from .models import Baias

from .forms import BaiasForm
from .forms import UpdateForm

def namedtuplefetchall(cursor):
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


def listar_baias(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM Baias_baias  ORDER BY id", [])
        #resultado = cursor.fetchall()

        resultado = namedtuplefetchall(cursor)
    return render(request, 'Baia/listar.html',
                  {'baias': resultado}
                  )
class listar_baias_lv(ListView):
    model = Baias
    template_name = "Baia/listar_lv.html"              

def adicionar_baia(request):
    if request.method == 'POST':
        form = BaiasForm(request.POST)
        if form.is_valid():
            nome_baia = form.cleaned_data['nome_baia']
            capacidade = form.cleaned_data['capacidade']
            definicao = form.cleaned_data['definicao']
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO Baias_baias (nome_baia, capacidade, definicao) "
                               "VALUES (%s, %s, %s)",
                               [nome_baia, capacidade, definicao])
                resultado = cursor.fetchall()
            return redirect('baias:listar')
    else:
        form = BaiasForm()
    return render(request, 'Baia/adicionar.html',
                  {'form': form}
                  )
class adicionar_baias_cv(CreateView):
    model = Baias
    template_name = "Baia/adicionar_cv.html"
    fields = ['nome_baia', 'capacidade', 'definicao', 'Funcionarios' ]
    success_url = reverse_lazy('baias:listar_lv')

    def form_valid(self, form):
        if Baias.objects.filter(nome_baia = form.cleaned_data['nome_baia']):
            messages.add_message(self.request, messages.WARNING,
                                 "Já existe uma Baia com esse nome.")
            return self.render_to_response(self.get_context_data(form=form))
        else:
            return super(adicionar_baias_cv, self).form_valid(form)                

def deletar_baia(request, pk):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias WHERE id=%s", [pk])
            nome_baia = cursor.fetchall()[0][1]

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias_Funcionarios WHERE baias_id=%s", [pk])
            resultado_baia_id = cursor.fetchall()
            cursor.execute("SELECT * FROM Animal_animal WHERE baia_id=%s", [pk])
            resultado_animal_baia_id = cursor.fetchall()

        if len(resultado_baia_id and resultado_animal_baia_id ) == 0:
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM Baias_baias WHERE id=%s", [pk])
            messages.add_message(request, messages.ERROR, 'Baia ' + nome_baia + ' deletado com sucesso.')
            return redirect('baias:listar')

        else:
            if len(resultado_baia_id) > 0:
                with connection.cursor() as cursor:
                    cursor.execute("DELETE FROM Baias_baias_Funcionarios WHERE baias_id=%s", [pk])
                messages.add_message(request, messages.ERROR, 'Funcionários desvinculados da ' + nome_baia + '.')
            if len(resultado_animal_baia_id) > 0:
                with connection.cursor() as cursor:
                  cursor.execute("UPDATE Animal_animal SET baia_id=null "
                                "WHERE baia_id=%s",
                                  [pk])
                messages.add_message(request, messages.ERROR, 'Animais desvinculados da ' + nome_baia + '.')
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM Baias_baias WHERE id=%s", [pk])
            messages.add_message(request, messages.ERROR, 'Baia ' + nome_baia + ' deletado com sucesso.')
            return redirect('baias:listar')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias WHERE id=%s", [pk])
            resultado = namedtuplefetchall(cursor)
        return render(request, "Baia/confirmar_deletar.html", {'baia': resultado[0]})
class deletar_baia_dv(DeleteView):
    model = Baias
    template_name = "Baia/confirmar_deletar_dv.html"
    success_url = reverse_lazy('baias:listar_lv')
 

def editar_baia(request, pk):
    if request.method == 'POST':
        form = UpdateForm(request.POST)
        if form.is_valid():
            nome_baia = form.cleaned_data['nome_baia']
            capacidade = form.cleaned_data['capacidade']
            definicao = form.cleaned_data['definicao']

            with connection.cursor() as cursor:
                cursor.execute("UPDATE Baias_baias SET nome_baia=%s, capacidade=%s, "
                               "definicao=%s WHERE id=%s",
                                [nome_baia, capacidade, definicao, pk])
                resultado = cursor.fetchall()
            return redirect('baias:listar')
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Baias_baias  WHERE id=%s", [pk])
            resultado_baia = namedtuplefetchall(cursor)
        form = UpdateForm(initial={'nome_baia': resultado_baia[0].nome_baia,
                                    'capacidade': resultado_baia[0].capacidade,
                                    'definicao': resultado_baia[0].definicao,
                                    })
    return render(request, 'Baia/editar.html',
                {'form': form}
                )

class editar_baia_uv(UpdateView):
    model = Baias
    fields = ['nome_baia', 'capacidade', 'definicao', 'Funcionarios' ]
    template_name = "Baia/editar_uv.html"
    success_url = reverse_lazy('baias:listar_lv')

templates/Baia/adicionar.html
{% extends "base.html" %}

{% block titulo %}
Adicionar Animais
{% endblock %}

{% block titulo_pagina %}
Cadastrar
{% endblock %}

{% block conteudo %}
  <div class="w-50 formulario">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Cadastrar">
    </form>
  </div>
{% endblock %}

templates/Baia/adicionar_cv.html
{% extends "base.html" %}

{% block titulo %}
Adicionar Baias CV
{% endblock %}

{% block titulo_pagina %}
Adicionar Baias CV

{% endblock %}

{% block conteudo %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    
    <div class="w-50 formulario">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
{% endblock %}

templates/Baia/confirmar_deletar.html
{% extends "base.html" %}

{% block titulo %}
Confirmação remoção
{% endblock %}

{% block titulo_pagina %}
Você tem certeza que deseja remover esta baia?
{% endblock %}

{% block conteudo %}
  <div class="w-25 mt-4">
    <form method="post">
      {% csrf_token %}
      <p><strong>Nome: </strong> {{baia.nome_baia}} </p>
      <p><strong>Capacidade: </strong> {{baia.capacidade}} </p>
      <p><strong>Definicao: </strong> {{baia.definicao}} </p>
      <input type="submit" class="btn btn-primary" value="Confirmar">
    </form>
  </div>

{% endblock %}

templates/Baia/confirmar_deletar_dv.html
{% extends "base.html" %}

{% block titulo %}
Confirmação remoção
{% endblock %}

{% block titulo_pagina %}
Você tem certeza que deseja remover esta baia?
{% endblock %}

{% block conteudo %}
  <div class="w-25 mt-4">
    <form method="post">
      {% csrf_token %}
      <p><strong>Nome: </strong> {{object.nome_baia}} </p>
      <p><strong>Tipo: </strong> {{object.capacidade}} </p>
      <input type="submit" class="btn btn-primary" value="Confirmar">
    </form>
  </div>

{% endblock %}

templates/Baia/deletar_dv.html
{% extends "base.html" %}

{% block titulo %}
Confirmação remoção
{% endblock %}

{% block titulo_pagina %}
Você tem certeza que deseja remover este funcionario?
{% endblock %}

{% block conteudo %}
  <div class="w-25 mt-4">
    <form method="post">
      {% csrf_token %}
      <p><strong>Nome: </strong> {{object.nome}} </p>
      <p><strong>Descrição: </strong> {{object.funcao}} </p>
      <input type="submit" class="btn btn-primary" value="Confirmar">
    </form>
  </div>

{% endblock %}

templates/Baia/editar.html
{% extends "base.html" %}

{% block titulo %}
Editar Funcionários
{% endblock %}

{% block titulo_pagina %}
Editar
{% endblock %}

{% block conteudo %}
  <div class="w-50">
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-primary" value="Atualizar">
    </form>
  </div>

{% endblock %}

templates/Baia/editar_uv.html
{% extends "base.html" %}

{% block titulo %}
Editar Baias DV
{% endblock %}

{% block titulo_pagina %}
Editar
{% endblock %}

{% block conteudo %}
  <div class="w-50 formulario">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Atualizar">
    </form>
  </div>

{% endblock %}

templates/Baia/listar.html
{% extends "base.html" %}

{% block titulo %}
Listar Baias
{% endblock %}

{% block titulo_pagina %}
Baias
{% endblock %}

{% block conteudo %}

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="alert alert-warning">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if baias %}
    <ul class="list-group div35">
        {% for baia in baias %}
        <li class="list-group-item">
                <strong>{{baia.id}}: {{ baia.nome_baia }}</strong>
                <span class="span">
                  <a href="{% url 'baias:editar' pk=baia.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
                    <i class="fas fa-pencil" style="color:#F2BE24"></i>
                  </a>
                  <a href="{% url 'baias:deletar' pk=baia.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
                    <i class="fas fa-trash" style="color: var(--main-red)"></i>
                  </a>
                </span>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Não há baias cadastradas.</p>
    {% endif %}
{% endblock %}

templates/Baia/listar_lv.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{% static 'ranchcontrol/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'ranchcontrol/styles.css' %}">

  <title>Ranch Control - web</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-dark navbar-expand-md" style="background-color: var(--main-light-green);">
      <div class="container-fluid">
        <a class="navbar-brand ms-5" href="http://localhost:8000/">
          <img src="{% static 'ranchcontrol/vaqueiro.svg' %}" alt="" width="30" height="24"
            class="d-inline-block align-text-top">
          Ranch Control
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Funcionarios
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/funcionario/adicionar">Adicionar</a></li>
                <li><a class="dropdown-item" href="http://localhost:8000/funcionario/listar">Listar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/funcionario/listar_lv">Listar LV</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Animal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/animal/adicionar">Adicionar</a></li>
                <li><a class="dropdown-item" href="http://localhost:8000/animal/listar">Listar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/animal/listar_lv">Listar LV</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Baias
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="http://localhost:8000/baias/adicionar">Adicionar</a></li>
                <li><a class="dropdown-item" href="http://localhost:8000/baias/listar">Listar</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="http://localhost:8000/baias/listar_lv">Listar LV</a></li>
              </ul>
            </li>
          </ul>
      </div>
    </nav>
  </header>

  <main class="container mt-5">
    <h3>
      Listar Baias LV
    </h3>
    
    {% if object_list %}
    <ul class="list-group div35">
      {% for baia in object_list  %}
      <li class="list-group-item">
        <strong>{{baia.id}}: {{ baia.nome_baia }} - {{ baia.definicao }}</strong>
        <span class="span">
          <a href="{% url 'baias:editar_uv' pk=baia.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-pencil" style="color:#F2BE24"></i>
          </a>
          <a href="{% url 'baias:deletar_dv' pk=baia.id %}" class="mx-2" style="text-decoration:none; text-align: end;">
            <i class="fas fa-trash" style="color: var(--main-red)"></i>
          </a>
        </span>
      </li>
      {% endfor %}
    </ul>
  {% else %}
  <p>Não há baias cadastradas.</p>
  {% endif %}
   
  </main>

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{% static 'ranchcontrol/script.js' %}"></script>
</body>

</html>